CREATE TABLE Armoire (
  idArmoire INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL ,
  Nom VARCHAR(255) DEFAULT NULL ,
  AdresseIP VARCHAR(15) NOT NULL
);

INSERT INTO Armoire (Nom,AdresseIP) VALUES('Salle C01','192.168.52.2');
INSERT INTO Armoire (Nom,AdresseIP) VALUES('Salle A02','192.168.52.3');
